baseurl = "https://blog.aiiane.com/"
languageCode = "en-us"
title = "Works by Default"
author = "Amber Yust"

pygmentsuseclasses = true
publishdir = "public"
builddrafts = false

theme = "cocoa"

[permalinks]
fixed = ":title/"
blog = ":year/:month/:slug/"

[params]
Title = "Works by Default"
Author = "Amber Yust"
GitHub = "https://github.com/ayust"
Lang = "en"
Twitter = "https://twitter.com/aiiane"
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "A blog."
HighlightJS = true

[taxonomies]
tag = "tags"
